site:
    name: FunkeLab
    site: 'https://lab.die-funke.de'
    base: '/'
    trailingSlash: false

    googleSiteVerificationId: orcPxI47GSa-cRvY11tUe6iGg2IO_RPvnA1q95iEM3M

# Default SEO metadata
metadata:
    title:
        default: FunkeLab
        template: '%s — FunkeLab'
    description: "\U0001F680 Makerspace der Funke e.V. Karlsruhe."
    robots:
        index: true
        follow: true
    openGraph:
        site_name: FunkeLab
        images:
            - url: '~/assets/images/default.png'
              width: 1200
              height: 628
        type: website
    twitter:
        handle: '@onwidget'
        site: '@onwidget'
        cardType: summary_large_image

i18n:
    language: de
    textDirection: ltr

analytics:
    vendors:
        googleAnalytics:
            id: null # or "G-XXXXXXXXXX"

ui:
    theme: 'system' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
